#!/bin/sh


python reproduce_2d_models.py -d Cpf1 -s 192 -p 0.05 -o ../models/Cpf1OfftargetsLC_cnn_elbo_0.05_
python reproduce_2d_models.py -d Cpf1 -s 192 -p 0.1 -o ../models/Cpf1OfftargetsLC_cnn_elbo_0.1_
python reproduce_2d_models.py -d Cpf1 -s 192 -p 0.2 -o ../models/Cpf1OfftargetsLC_cnn_elbo_0.2_
python reproduce_2d_models.py -d Cpf1 -s 192 -p 0.3 -o ../models/Cpf1OfftargetsLC_cnn_elbo_0.3_
python reproduce_2d_models.py -d Cpf1 -s 192 -p 0.4 -o ../models/Cpf1OfftargetsLC_cnn_elbo_0.4_
python reproduce_2d_models.py -d Cpf1 -s 192 -p 0.5 -o ../models/Cpf1OfftargetsLC_cnn_elbo_0.5_
python reproduce_2d_models.py -d Cpf1 -s 192 -p 0.75 -o ../models/Cpf1OfftargetsLC_cnn_elbo_0.75_
python reproduce_2d_models.py -d Cpf1 -s 192 -p 0.9 -o ../models/Cpf1OfftargetsLC_cnn_elbo_0.9_
python reproduce_2d_models.py -d Cpf1 -s 192 -p 0.95 -o ../models/Cpf1OfftargetsLC_cnn_elbo_0.95_
python reproduce_2d_models.py -d Cpf1 -s 192 -p 0.99 -o ../models/Cpf1OfftargetsLC_cnn_elbo_0.99_

python reproduce_2d_models.py -d Cpf1 -s 192 -p 0.05 -o ../models/Cpf1OfftargetsLC_cnn_mse_0.05_ -u
python reproduce_2d_models.py -d Cpf1 -s 192 -p 0.1 -o ../models/Cpf1OfftargetsLC_cnn_mse_0.1_ -u
python reproduce_2d_models.py -d Cpf1 -s 192 -p 0.2 -o ../models/Cpf1OfftargetsLC_cnn_mse_0.2_ -u
python reproduce_2d_models.py -d Cpf1 -s 192 -p 0.3 -o ../models/Cpf1OfftargetsLC_cnn_mse_0.3_ -u
python reproduce_2d_models.py -d Cpf1 -s 192 -p 0.4 -o ../models/Cpf1OfftargetsLC_cnn_mse_0.4_ -u
python reproduce_2d_models.py -d Cpf1 -s 192 -p 0.5 -o ../models/Cpf1OfftargetsLC_cnn_mse_0.5_ -u
python reproduce_2d_models.py -d Cpf1 -s 192 -p 0.75 -o ../models/Cpf1OfftargetsLC_cnn_mse_0.75_ -u
python reproduce_2d_models.py -d Cpf1 -s 192 -p 0.9 -o ../models/Cpf1OfftargetsLC_cnn_mse_0.9_ -u
python reproduce_2d_models.py -d Cpf1 -s 192 -p 0.95 -o ../models/Cpf1OfftargetsLC_cnn_mse_0.95_ -u
python reproduce_2d_models.py -d Cpf1 -s 192 -p 0.99 -o ../models/Cpf1OfftargetsLC_cnn_mse_0.99_ -u

python reproduce_2d_models.py -d Cpf1 -s 192 -p 0.05 -o ../models/Cpf1OfftargetsLC_rnn_elbo_0.05_
python reproduce_2d_models.py -d Cpf1 -s 192 -p 0.1 -o ../models/Cpf1OfftargetsLC_rnn_elbo_0.1_
python reproduce_2d_models.py -d Cpf1 -s 192 -p 0.2 -o ../models/Cpf1OfftargetsLC_rnn_elbo_0.2_
python reproduce_2d_models.py -d Cpf1 -s 192 -p 0.3 -o ../models/Cpf1OfftargetsLC_rnn_elbo_0.3_
python reproduce_2d_models.py -d Cpf1 -s 192 -p 0.4 -o ../models/Cpf1OfftargetsLC_rnn_elbo_0.4_
python reproduce_2d_models.py -d Cpf1 -s 192 -p 0.5 -o ../models/Cpf1OfftargetsLC_rnn_elbo_0.5_
python reproduce_2d_models.py -d Cpf1 -s 192 -p 0.75 -o ../models/Cpf1OfftargetsLC_rnn_elbo_0.75_
python reproduce_2d_models.py -d Cpf1 -s 192 -p 0.9 -o ../models/Cpf1OfftargetsLC_rnn_elbo_0.9_
python reproduce_2d_models.py -d Cpf1 -s 192 -p 0.95 -o ../models/Cpf1OfftargetsLC_rnn_elbo_0.95_
python reproduce_2d_models.py -d Cpf1 -s 192 -p 0.99 -o ../models/Cpf1OfftargetsLC_rnn_elbo_0.99_

python reproduce_2d_models.py -d Cpf1 -s 192 -p 0.05 -o ../models/Cpf1OfftargetsLC_rnn_mse_0.05_ -u
python reproduce_2d_models.py -d Cpf1 -s 192 -p 0.1 -o ../models/Cpf1OfftargetsLC_rnn_mse_0.1_ -u
python reproduce_2d_models.py -d Cpf1 -s 192 -p 0.2 -o ../models/Cpf1OfftargetsLC_rnn_mse_0.2_ -u
python reproduce_2d_models.py -d Cpf1 -s 192 -p 0.3 -o ../models/Cpf1OfftargetsLC_rnn_mse_0.3_ -u
python reproduce_2d_models.py -d Cpf1 -s 192 -p 0.4 -o ../models/Cpf1OfftargetsLC_rnn_mse_0.4_ -u
python reproduce_2d_models.py -d Cpf1 -s 192 -p 0.5 -o ../models/Cpf1OfftargetsLC_rnn_mse_0.5_ -u
python reproduce_2d_models.py -d Cpf1 -s 192 -p 0.75 -o ../models/Cpf1OfftargetsLC_rnn_mse_0.75_ -u
python reproduce_2d_models.py -d Cpf1 -s 192 -p 0.9 -o ../models/Cpf1OfftargetsLC_rnn_mse_0.9_ -u
python reproduce_2d_models.py -d Cpf1 -s 192 -p 0.95 -o ../models/Cpf1OfftargetsLC_rnn_mse_0.95_ -u
python reproduce_2d_models.py -d Cpf1 -s 192 -p 0.99 -o ../models/Cpf1OfftargetsLC_rnn_mse_0.99_ -u
